//automatically generated ROOT DICT definition
//!!! DO NOT EDIT THIS FILE !!!
//add further class definitions to the DICTHEADERS variable in Makefile.am
#ifdef __CINT__
#pragma link off all globals;
#pragma link off all classes;
#pragma link off all functions;
#pragma link C++ namespace dcs;
#pragma link C++ namespace dcs::fee;
#pragma link C++ class dcs::fee::FeeSampleClient;
#pragma link C++ class dcs::fee::FeeClientLibInterface;
#pragma link C++ class dcs::fee::AckData;
#endif
